[package]
name = "rust-practice-json-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.12"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
unused_imports = "allow"